### ISSUE TITLE
配置好后，一直报这个错

### ISSUE THREAD

**Issue by dxtywt** [sdvdxl/falcon-message#1]
"level":"ERROR","prefix":"echo","file":"echo.go","line":"284","message":"code=404, message=Not Found
请问这个是什么问题呢

**Comment by sdvdxl** [comment]
怎么运行的？这里面没有echo.go 文件，这个日志是哪里的

**Comment by lemon9921010** [comment]
+1

**Comment by sdvdxl** [comment]
接口是 http://ip:port/api/v1
