### ISSUE TITLE
您好，我在编译后运行时出现如下信息，请问如何解决，先谢谢了

### ISSUE THREAD

**Issue by pushimao** [sdvdxl/falcon-message#3]
刚接触open-falcon监控，希望实现钉钉消息推送，在按照说明配置后，运行时出现如下信息：
{"time":"2018-03-10T09:59:37.738326163+08:00","level":"ERROR","prefix":"echo","file":"echo.go","line":"286","message":"code=404, message=Not Found"}
相关的alarm日志是这样的：
time="2018-03-10T09:59:37+08:00" level=debug msg="write im to queue, im:<Tos:[ding]:ff6945e588a3e89a61da0dd9575f561c75b9f682e8e669161e5f8168b37783fa, Content:[P0][OK][02-2c2g][][ all(#3) cpu.user  0.5<0][O1 2018-03-10 09:59:00]>, queue:/im" 

time="2018-03-10T09:59:37+08:00" level=debug msg="send im:<Tos:[ding]:ff6945e588a3e89a61da0dd9575f561c75b9f682e8e669161e5f8168b37783fa, Content:[P0][OK][02-2c2g][][ all(#3) cpu.user  0.5<0][O1 2018-03-10 09:59:00]>, resp:{\"message\":\"Not Found\"}, url:http://127.0.0.1:23329/api/v1" 

请问可以帮我分析一下嘛，表示非常感谢！

**Comment by sdvdxl** [comment]
地址换成 [http://localhost:23329/api/v1/message](http://localhost:23329/api/v1/message)，后来改了一版，打算加上email，路径换了

**Comment by pushimao** [comment]
谢谢指教！

**Comment by pushimao** [comment]
钉钉成功收到告警消息，谢谢！另外新版的main.go中的第69行多了一个"w"，希望可以修改一下

**Comment by sdvdxl** [comment]
多谢，今天修改readme，不小心敲上的
