### ISSUE TITLE
执行control build提示下列错误

### ISSUE THREAD

**Issue by ravecn** [sdvdxl/falcon-message#4]
./control build
/root/go/src/github.com/sdvdxl/falcon-message/sender/wexin.go:18:2: cannot find package "github.com/sdvdxl/go-tools/encrypt" in any of:
        /usr/lib/golang/src/github.com/sdvdxl/go-tools/encrypt (from $GOROOT)
        /root/go/src/github.com/sdvdxl/go-tools/encrypt (from $GOPATH)
main.go:15:2: cannot find package "github.com/tylerb/graceful" in any of:
        /usr/lib/golang/src/github.com/tylerb/graceful (from $GOROOT)
        /root/go/src/github.com/tylerb/graceful (from $GOPATH)
/root/go/src/github.com/sdvdxl/dinghook/dinghook.go:15:2: cannot find package "gopkg.in/go-playground/validator.v9" in any of:
        /usr/lib/golang/src/gopkg.in/go-playground/validator.v9 (from $GOROOT)
        /root/go/src/gopkg.in/go-playground/validator.v9 (from $GOPATH)

**Comment by sdvdxl** [comment]
go get

**Comment by benbenpi** [comment]
执行./control start报错：falcon-message failed to start.
./control tail
nohup: failed to run command `./falcon-message': No such file or directory

**Comment by zhangbin0027** [comment]
我也遇到了这个问题
执行./control start报错：falcon-message无法启动。
./control tail 
nohup：无法运行命令`./falcon-message'：没有这样的文件或目录

**Comment by sdvdxl** [comment]
需要先编译

**Comment by zhangbin0027** [comment]
hi，sdvdxl

control build后，把所有依赖都go get后出现这个错误
mv: cannot stat ‘message’: No such file or directory
2018/08/26 23:11:58 listening on  127.0.0.1:23329

                                                 Bestwishes，zhangbin

**Comment by zhangbin0027** [comment]
将falcon-message目录名改为message后
[root@localhost message]# ./control build
2018/08/26 23:21:25 listening on  localhost:23329
请问是成功启动了么？
[root@localhost message]# ./control start
./control: line 43: var/app.pid: Is a directory
falcon-message started..., pid=5451

**Comment by sdvdxl** [comment]
pull一下，我更新了下control这个脚本
