### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by mognum** [sdvdxl/falcon-message#5]
$ glide rebuild
[WARN]  The rebuild command is deprecated and will be removed in a future version
[WARN]  Use the go install command instead
[WARN]  The name listed in the config file (github.com/sdvdxl/falcon-message) does not match the current location (falcon-message)
[INFO]  Building dependencies.
[INFO]  Running go build github.com/labstack/echo/middleware
[INFO]  Running go build github.com/tylerb/graceful
[INFO]  Running go build golang.org/x/sys
[WARN]  Failed to run 'go install' for golang.org/x/sys: can't load package: package falcon-message/vendor/golang.org/x/sys: no Go files in /root/workspace/src/falcon-message/vendor/golang.org/x/sys

[INFO]  Running go build golang.org/x/crypto
[WARN]  Failed to run 'go install' for golang.org/x/crypto: can't load package: package falcon-message/vendor/golang.org/x/crypto: no Go files in /root/workspace/src/falcon-message/vendor/golang.org/x/crypto

而文件是存在的
$ ls /root/workspace/src/falcon-message/vendor/golang.org/x/crypto
acme     bcrypt   blake2s   bn256  chacha20poly1305  CONTRIBUTING.md  cryptobyte  ed25519  LICENSE  nacl  openpgp  PATENTS  pkcs12    README     salsa20  sha3  tea      xtea
AUTHORS  blake2b  blowfish  cast5  codereview.cfg    CONTRIBUTORS     curve25519  hkdf     md4      ocsp  otr      pbkdf2   poly1305  ripemd160  scrypt   ssh   twofish  xts

**Comment by sdvdxl** [comment]
#6
