### ISSUE TITLE
只发送成功了一次告警，返回errmsg":"token is not exist","errcode":300001，请问是否是协议头问题？

### ISSUE THREAD

**Issue by zhangbin0027** [sdvdxl/falcon-message#7]
2018/08/30 22:41:26 message comming
2018/08/30 22:41:26 tos: [ding]:b10deee3d9e2dbc21ce57eb9f80da23a643ebe83154dd6b086486da2c833acb6,b10deee3d9e2dbc21ce57eb9f80da23a643ebe83154dd6b086486da2c833acb6  content: [P0][PROBLEM][root][][CPU空闲率大于%50 all(#1) cpu.idle  98.96907>=0.9][O4 2018-08-30 22:41:00]
2018/08/30 22:41:26 message: {"at":{"atMobiles":null,"isAtAll":false},"msgtype":"text","text":{"content":"P0\nPROBLEM\nroot\n\nCPU空闲率大于%50 all(#1) cpu.idle  98.96907\u003e=0.9\nO4 2018-08-30 22:41:00"}}
2018/08/30 22:41:26 response result: {"errmsg":"token is not exist","errcode":300001}
2018/08/30 22:41:26 {false token is not exist 300001}
2018/08/30 22:41:26 token: b10deee3d9e2dbc21ce57eb9f80da23a643ebe83154dd6b086486da2c833acb6,b10deee3d9e2dbc21ce57eb9f80da23a643ebe83154dd6b086486da2c833acb6

**Comment by zhangbin0027** [comment]
换了一个webhook地址后又成功发送，但是看日志返回300001有问题吗？

**Comment by zhangbin0027** [comment]
2018/08/30 22:59:13 message: {"at":{"atMobiles":null,"isAtAll":false},"msgtype":"text","text":{"content":"P0\nPROBLEM\nroot\n\n磁盘io利用率小于50% all(#3) cpu.iowait  0\u003c=50\nO3 2018-08-30 22:59:00"}}
2018/08/30 22:59:13 response result: {"errmsg":"ok","errcode":0}
2018/08/30 22:59:13 {true ok 0}
看日志，这样应该是成功的

**Comment by sdvdxl** [comment]
注意，需要修改mysql 中 uic库中的user表，把im字段的大小改为4000（防止钉钉token溢出截断，不生效）。 看一下这个字段长度是多少，是不是截断的问题

**Comment by xiaoyang16889** [comment]
> 2018/08/30 22:41:26消息
> 来源2018/08/30 22:41:26 tos：[ding]：b10deee3d9e2dbc21ce57eb9f80da23a643ebe83154dd6b086486da2c833acb6，b10deee3d9e2dbc21ce57eb9f80da23a643ebe83154dd6b086486da2c833acb6内容：[P0] [问题] [root] [] [CPU空闲率大于％ 50全部（[＃1](https://github.com/sdvdxl/falcon-message/issues/1)）cpu.idle 98.96907> = 0.9] [O4 2018-08-30 22:41:00] 
> 2018/08/30 22:41:26消息：{“at”：{“atMobiles”：null ，“isAtAll”：false}，“msgtype”：“text”，“text”：{“content”：“P0 \ nPROBLEM \ nroot \ n \ nCPU空闲率大于％50 all（[＃1](https://github.com/sdvdxl/falcon-message/issues/1)）cpu.idle 98.96907 \ u003e = 0.9 \ nO4 2018-08-30 22:41:00“}} 
> 2018/08/30 22:41:26响应结果：{”errmsg“：”令牌不存在“，”errcode“：300001} 
> 2018 / 08/30 22:41:26 {假令牌不存在300001}
> 2018年8月30日22点41分26秒令牌：b10deee3d9e2dbc21ce57eb9f80da23a643ebe83154dd6b086486da2c833acb6，b10deee3d9e2dbc21ce57eb9f80da23a643ebe83154dd6b086486da2c833acb6

能指导下钉钉报警吗？

**Comment by sdvdxl** [comment]
> > 2018年8月30日22点41分26秒令牌：b10deee3d9e2dbc21ce57eb9f80da23a643ebe83154dd6b086486da2c833acb6，b10deee3d9e2dbc21ce57eb9f80da23a643ebe83154dd6b086486da2c833acb6
> 
> 能指导下钉钉报警吗？

令牌重复了吧，另外不要把敏感信息贴出来，抓紧换token吧

**Comment by xiaoyang16889** [comment]
@zhangbin0027

**Comment by xiaoyang16889** [comment]
@zhangbin0027 ：可以远程协助下吗，有偿协助哦，q907512653
